apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-production
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-production
  template:
    metadata:
      labels:
        app: my-app-production
    spec:
      containers:
        - name: my-app
          image: myapp:latest
          ports:
            - containerPort: 80

