apiVersion: v1
kind: Service
metadata:
  name: my-app-production
  namespace: production
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: my-app-production

