apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-dev
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-dev
  template:
    metadata:
      labels:
        app: my-app-dev
    spec:
      containers:
        - name: my-app
          image: myapp:dev
          ports:
            - containerPort: 80

