apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-staging
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-staging
  template:
    metadata:
      labels:
        app: my-app-staging
    spec:
      containers:
        - name: my-app
          image: myapp:staging
          ports:
            - containerPort: 80

